import os

env_vars = {}

# 1. Try to read from local .env file
try:
    with open('.env', 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and '=' in line and not line.startswith('#'):
                key, val = line.split('=', 1)
                env_vars[key.strip()] = val.strip()
except FileNotFoundError:
    print("No .env file found. Falling back to system environment variables (Netlify build environment).")

# 2. Check if variables are provided in os.environ (Netlify / CI overrides local .env)
expected_keys = [
    'SUPABASE_URL', 
    'SUPABASE_ANON_KEY', 
    'CLOUDINARY_CLOUD', 
    'CLOUDINARY_PRESET_COMPLAINTS', 
    'CLOUDINARY_PRESET_VERIFICATION'
]

for key in expected_keys:
    if key in os.environ:
        env_vars[key] = os.environ[key]

# 3. Write to the frontend JS config file
os.makedirs('frontend/js', exist_ok=True)
output_path = 'frontend/js/env.js'

with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by build_env.py. DO NOT EDIT DIRECTLY.\n')
    f.write('window.ENV = {\n')
    for key, val in env_vars.items():
        # Using json.dumps-like escaping for safety
        val_escaped = val.replace('\\', '\\\\').replace('"', '\\"')
        f.write(f'    "{key}": "{val_escaped}",\n')
    f.write('};\n')

print(f"✅ Generated {output_path} successfully with {len(env_vars)} variables.")

# 4. Copy the media folder into frontend so Netlify can serve it
import shutil
media_src = 'media'
media_dst = 'frontend/media'

if os.path.exists(media_src):
    # Only copy if dst does NOT exist or if we want to overwrite, but lets just copy files missing
    if not os.path.exists(media_dst):
        print(f"Copying {media_src} to {media_dst}...")
        shutil.copytree(media_src, media_dst)
    else:
        # Simple file sync
        for item in os.listdir(media_src):
            s = os.path.join(media_src, item)
            d = os.path.join(media_dst, item)
            if os.path.isfile(s):
                shutil.copy2(s, d)
    print("✅ Media folder copied successfully.")
else:
    print("⚠️ Media folder not found.")
