import os

env_vars = {}

# 1. Try to read from local .env file
try:
    with open('.env', 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and '=' in line and not line.startswith('#'):
                key, val = line.split('=', 1)
                env_vars[key.strip()] = val.strip()
except FileNotFoundError:
    print("No .env file found. Falling back to system environment variables (Netlify build environment).")

# 2. Check if variables are provided in os.environ (Netlify / CI overrides local .env)
expected_keys = [
    'SUPABASE_URL', 
    'SUPABASE_ANON_KEY', 
    'CLOUDINARY_CLOUD', 
    'CLOUDINARY_PRESET_COMPLAINTS', 
    'CLOUDINARY_PRESET_VERIFICATION'
]

for key in expected_keys:
    if key in os.environ:
        env_vars[key] = os.environ[key]

# 3. Write to the frontend JS config file
os.makedirs('frontend/js', exist_ok=True)
output_path = 'frontend/js/env.js'

with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by build_env.py. DO NOT EDIT DIRECTLY.\n')
    f.write('window.ENV = {\n')
    for key, val in env_vars.items():
        # Using json.dumps-like escaping for safety
        val_escaped = val.replace('\\', '\\\\').replace('"', '\\"')
        f.write(f'    "{key}": "{val_escaped}",\n')
    f.write('};\n')

print(f"✅ Generated {output_path} successfully with {len(env_vars)} variables.")
